obj-y += thread_led.o
obj-y += thread_key.o
obj-y += thread_mqtt.o
obj-y += thread_usart_rceive.o
obj-y += thread_usart_send.o
obj-y += thread_usart_handle.o

obj-y += thread_device.o
obj-y += thread_execute.o
obj-y += thread_report.o
obj-y += thread_scene.o
obj-y += thread_timer.o